apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          # 將此映像改為你的 Harbor 倉庫，例如: harbor.example.com/project/demo-app:latest
          image: nginx:alpine
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: harbor-regcred
