grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
    hosts:
      - grafana.czhuang.dev   # 之後可再用 external-dns 自動綁定
  defaultDashboardsEnabled: true

prometheus:
  ingress:
    enabled: false

alertmanager:
  ingress:
    enabled: false
