name: ci-cd

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "gitops/**"   # 依需要調整
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 需要能 push 回 repo 更新 tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GHA_ROLE_ARN }}
          aws-region: ap-southeast-2
          # role-session-name 可選
          # role-duration-seconds 可選（預設 1 小時）

      - name: Set vars
        id: vars
        run: |
          echo "IMAGE=${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/tickboard" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_REGISTRY }} \
            -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }} .
          docker tag  ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }} ${{ steps.vars.outputs.IMAGE }}:latest

      # （可選）Trivy 掃描
      # - uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}
      #     format: 'table'
      #     exit-code: '0'

      - name: Push image
        run: |
          docker push ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ steps.vars.outputs.IMAGE }}:latest

      - name: Update image tag in gitops manifests
        run: |
          FILE="gitops/stacks/tickboard/deployment.yaml"
          sed -i "s#harbor.czhuang.dev/.*/tickboard:.*#${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}#g" $FILE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $FILE
          git commit -m "ci: update tickboard image to ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}"
          git push
