name: CI to Harbor and GitOps update

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - '.github/workflows/harbor-ci.yml'
      - 'k8s/**'
  workflow_dispatch:

env:
  IMAGE_NAME: demo-app
  REGISTRY: ${{ secrets.HARBOR_HOST }}
  PROJECT: ${{ secrets.HARBOR_PROJECT }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:latest

      - name: Update k8s deployment image
        run: |
          NEW_IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          # Replace the image line in deployment.yaml while preserving indentation (portable to GNU/BSD sed)
          sed -i -E "s|^([[:space:]]*)image: .*|\\1image: ${NEW_IMAGE}|" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add k8s/deployment.yaml
          if ! git diff --cached --quiet; then
            git commit -m "chore(ci): update image to ${NEW_IMAGE} [skip ci]"
            git push
